// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyVersionAttribute("0.1.0")>]
[<assembly: AssemblyFileVersionAttribute("0.1.0")>]
[<assembly: AssemblyTitleAttribute("FsProfiler")>]
[<assembly: AssemblyProductAttribute("Fracer")>]
[<assembly: AssemblyDescriptionAttribute("")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyVersion = "0.1.0"
    let [<Literal>] AssemblyFileVersion = "0.1.0"
    let [<Literal>] AssemblyTitle = "FsProfiler"
    let [<Literal>] AssemblyProduct = "Fracer"
    let [<Literal>] AssemblyDescription = ""
